# Generated by Django 4.1.2 on 2022-10-22 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wep_app', '0002_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='image',
            field=models.ImageField(default='null = True', upload_to='cart_img'),
            preserve_default=False,
        ),
    ]
