# Generated by Django 4.1.2 on 2022-10-25 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wep_app', '0005_auto_20221024_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderby',
            name='prodect_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wep_app.cart'),
        ),
    ]
