# Generated by Django 4.1.2 on 2022-10-25 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wep_app', '0006_alter_orderby_prodect_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mail',
            field=models.EmailField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
