# Generated by Django 4.1.2 on 2022-10-25 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wep_app', '0007_user_mail_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='order',
            field=models.BooleanField(default=False, help_text='0-Add, 1-Remove'),
        ),
    ]
