# Generated by Django 4.1.2 on 2022-10-26 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wep_app', '0010_orderby_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderby',
            name='prodect_name',
        ),
        migrations.AddField(
            model_name='orderby',
            name='prodect_name',
            field=models.ManyToManyField(to='wep_app.cart'),
        ),
    ]
