# Generated by Django 4.1.2 on 2022-10-28 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wep_app', '0011_remove_orderby_prodect_name_orderby_prodect_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderby',
            name='prodect_name',
        ),
        migrations.AddField(
            model_name='orderby',
            name='prodect_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wep_app.cart'),
        ),
    ]
