# Generated by Django 4.1.2 on 2022-10-28 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wep_app', '0012_remove_orderby_prodect_name_orderby_prodect_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=30, null=True)),
                ('image', models.ImageField(null=True, upload_to='cart_img')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('quantity', models.IntegerField(default=1)),
                ('order', models.BooleanField(default=False, help_text='0-Add, 1-Remove')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wep_app.prodect')),
            ],
        ),
    ]
