# Generated by Django 3.2.12 on 2022-10-28 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wep_app', '0013_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='prodect',
            name='added',
            field=models.BooleanField(default=False, help_text='0-show_cart_btn, 1-show_wish_btn'),
        ),
    ]
