# Generated by Django 4.1.2 on 2022-10-29 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wep_app', '0015_alter_prodect_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderby',
            name='current_price',
        ),
        migrations.RemoveField(
            model_name='orderby',
            name='image',
        ),
        migrations.RemoveField(
            model_name='orderby',
            name='original_price',
        ),
        migrations.RemoveField(
            model_name='orderby',
            name='tax',
        ),
        migrations.RemoveField(
            model_name='orderby',
            name='total',
        ),
        migrations.AddField(
            model_name='orderby',
            name='order_status',
            field=models.CharField(default='bending', max_length=40),
        ),
        migrations.RemoveField(
            model_name='orderby',
            name='prodect_name',
        ),
        migrations.AlterField(
            model_name='prodect',
            name='added',
            field=models.CharField(default='not_added', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='orderby',
            name='prodect_name',
            field=models.ManyToManyField(to='wep_app.cart'),
        ),
    ]
