# Generated by Django 4.1.2 on 2022-10-29 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wep_app', '0016_remove_orderby_current_price_remove_orderby_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderby',
            old_name='prodect_name',
            new_name='ordered_things',
        ),
    ]
