# Generated by Django 4.1.2 on 2022-10-29 11:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wep_app', '0017_rename_prodect_name_orderby_ordered_things'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderby',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
