# Generated by Django 4.1.2 on 2022-10-30 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wep_app', '0021_cart_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='order_status',
            field=models.CharField(default='not_order', max_length=40),
        ),
    ]
